# .streamlit/config.toml

[server]
# Max size of uploaded files in MB
maxUploadSize = 250
# Optional: Customize widget styling further if needed
# headless = false # Can sometimes help clean up minor UI elements if needed

[theme]
# Set the base theme to dark FIRST
# This ensures all default elements inherit dark styling
base="dark"

# Primary accent color for interactive elements. Keeping your green.
primaryColor="#2ECC71"

# Background color for the main content area (dark)
# Common dark choices: #0E1117 (Streamlit default), #1E1E1E, #1a1d21
backgroundColor="#0E1117"

# Background color used for the sidebar and most interactive widgets (usually slightly lighter/different dark)
# Common choices: #262730 (Streamlit default), #252526, #2c3035
secondaryBackgroundColor="#262730"

# Color used for most text (needs to be light for contrast)
# Common choices: #FAFAFA (Streamlit default), #FFFFFF, #E0E0E0
textColor="#FAFAFA"

# Font family for all text in the app, except code blocks.
# Keep as is unless you want to change it.
font="sans serif"

# Hide top right menu and footer (Keep your settings)
[ui]
hideTopBar = false

# Keep your settings
[browser]
gatherUsageStats = false

# Keep your settings
[runner]
magicEnabled = true
fastReruns = true