# Local development secrets file
# For Streamlit Cloud deployment, set these values in the Streamlit dashboard

# Placeholder for Google Drive file ID (replace with actual ID for testing)
# This is the ID portion from your Google Drive share link
SELECTOR_GDRIVE_URL = "1A9RK40Z93DOcdCXnl7KKidFbNOJOyaeo"

# For local development, you can set this to empty
# The app will fall back to loading from the local filesystem 
